version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: devopslab01-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - db_data:/var/lib/mysql  # persistent storage

  app:
    build: .
    container_name: devopslab01-app-1
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: devopsdb
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  db_data:
